export const accountFirstName = 'Jazmine' 
export const accountLastName = 'Isip' 
export const accountEmail = 'isipjazmine1@gmail.com' 
export const accountBirthDate = '2002-06-04'
export const accountContactNumber = '09123456789'
export const accountPosition = 'Admin'
export const accountTIN = '012345678910'
export const accountSSSNo = '123'
export const accountHDMFNo = '456'
export const accountPHICNo = '000'

export const emergencyContactFirstName = 'Thea'
export const emergencyContactLastName = 'Isip'
export const emergencyContactEmail = 'sample@gmail.com'
export const emergencyContactNumber = '09090900909'

export const fileName = 'profile.png'
export const fileType = 'image/png'